
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Monija
 */
public class Cake extends javax.swing.JFrame {

    /**
     * Creates new form Cake
     */
    public Cake() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        item = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        black = new javax.swing.JButton();
        blueberry = new javax.swing.JButton();
        cappuccino = new javax.swing.JButton();
        malted = new javax.swing.JButton();
        almond = new javax.swing.JButton();
        velvet = new javax.swing.JButton();
        strawberry = new javax.swing.JButton();
        rate7 = new javax.swing.JLabel();
        rate6 = new javax.swing.JLabel();
        rate5 = new javax.swing.JLabel();
        rate4 = new javax.swing.JLabel();
        rate3 = new javax.swing.JLabel();
        rate2 = new javax.swing.JLabel();
        rate1 = new javax.swing.JLabel();
        ImageLevel = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        vanilla = new javax.swing.JButton();
        dessert = new javax.swing.JButton();
        rate8 = new javax.swing.JLabel();
        rate9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CAKE");
        setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255), 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));

        title.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(0, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("CAKE");
        title.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        item.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        item.setForeground(new java.awt.Color(0, 255, 255));
        item.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        item.setText("Item List");
        item.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate.setForeground(new java.awt.Color(0, 255, 255));
        rate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate.setText("Rate");
        rate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        image.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        image.setForeground(new java.awt.Color(0, 255, 255));
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setText("Image");
        image.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        black.setBackground(new java.awt.Color(102, 0, 0));
        black.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        black.setForeground(new java.awt.Color(0, 255, 255));
        black.setText(" 1. Black Forest Cake");
        black.setBorder(null);
        black.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        black.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        black.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackActionPerformed(evt);
            }
        });

        blueberry.setBackground(new java.awt.Color(102, 0, 0));
        blueberry.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        blueberry.setForeground(new java.awt.Color(0, 255, 255));
        blueberry.setText(" 2. Blueberry Cake");
        blueberry.setBorder(null);
        blueberry.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        blueberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueberryActionPerformed(evt);
            }
        });

        cappuccino.setBackground(new java.awt.Color(102, 0, 0));
        cappuccino.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        cappuccino.setForeground(new java.awt.Color(0, 255, 255));
        cappuccino.setText(" 3. Cappuccino Cake");
        cappuccino.setBorder(null);
        cappuccino.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        cappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappuccinoActionPerformed(evt);
            }
        });

        malted.setBackground(new java.awt.Color(102, 0, 0));
        malted.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        malted.setForeground(new java.awt.Color(0, 255, 255));
        malted.setText(" 5. Malted Chocolate Cake");
        malted.setBorder(null);
        malted.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        malted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maltedActionPerformed(evt);
            }
        });

        almond.setBackground(new java.awt.Color(102, 0, 0));
        almond.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        almond.setForeground(new java.awt.Color(0, 255, 255));
        almond.setText(" 6. Pistachio Almond Cake\t");
        almond.setBorder(null);
        almond.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        almond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almondActionPerformed(evt);
            }
        });

        velvet.setBackground(new java.awt.Color(102, 0, 0));
        velvet.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        velvet.setForeground(new java.awt.Color(0, 255, 255));
        velvet.setText(" 7. Red Velvet Cake");
        velvet.setBorder(null);
        velvet.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        velvet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velvetActionPerformed(evt);
            }
        });

        strawberry.setBackground(new java.awt.Color(102, 0, 0));
        strawberry.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        strawberry.setForeground(new java.awt.Color(0, 255, 255));
        strawberry.setText(" 8. Strawberry Chocolate Cake");
        strawberry.setBorder(null);
        strawberry.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        strawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryActionPerformed(evt);
            }
        });

        rate7.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate7.setForeground(new java.awt.Color(0, 255, 255));
        rate7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate7.setText("800/-");
        rate7.setToolTipText("");
        rate7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate6.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate6.setForeground(new java.awt.Color(0, 255, 255));
        rate6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate6.setText("850/-");
        rate6.setToolTipText("");
        rate6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate5.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate5.setForeground(new java.awt.Color(0, 255, 255));
        rate5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate5.setText("950/-");
        rate5.setToolTipText("");
        rate5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate4.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate4.setForeground(new java.awt.Color(0, 255, 255));
        rate4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate4.setText("720/-");
        rate4.setToolTipText("");
        rate4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate3.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate3.setForeground(new java.awt.Color(0, 255, 255));
        rate3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate3.setText("980/-");
        rate3.setToolTipText("");
        rate3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate2.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate2.setForeground(new java.awt.Color(0, 255, 255));
        rate2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate2.setText("750/-");
        rate2.setToolTipText("");
        rate2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate1.setBackground(new java.awt.Color(153, 153, 255));
        rate1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate1.setForeground(new java.awt.Color(0, 255, 255));
        rate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate1.setText("850/-");
        rate1.setToolTipText("");
        rate1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        menu.setBackground(new java.awt.Color(102, 0, 0));
        menu.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        menu.setForeground(new java.awt.Color(0, 255, 255));
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(102, 0, 0));
        exit.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 255, 255));
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        vanilla.setBackground(new java.awt.Color(102, 0, 0));
        vanilla.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        vanilla.setForeground(new java.awt.Color(0, 255, 255));
        vanilla.setText(" 9. Vanilla Cake");
        vanilla.setBorder(null);
        vanilla.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        vanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vanillaActionPerformed(evt);
            }
        });

        dessert.setBackground(new java.awt.Color(102, 0, 0));
        dessert.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        dessert.setForeground(new java.awt.Color(0, 255, 255));
        dessert.setText(" 4. Chocolate Dessert Cake");
        dessert.setBorder(null);
        dessert.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        dessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessertActionPerformed(evt);
            }
        });

        rate8.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate8.setForeground(new java.awt.Color(0, 255, 255));
        rate8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate8.setText("730/-");
        rate8.setToolTipText("");
        rate8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate9.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate9.setForeground(new java.awt.Color(0, 255, 255));
        rate9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate9.setText("900/-");
        rate9.setToolTipText("");
        rate9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blueberry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(black, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(malted, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(almond, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(velvet, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(strawberry, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dessert, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rate9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rate1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rate2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rate3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rate4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rate5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rate6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rate7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rate8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ImageLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(image, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(ImageLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(black, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(blueberry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dessert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(malted, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(almond, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(velvet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(strawberry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(vanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(rate1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rate2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rate3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rate4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rate5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rate6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rate7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rate8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rate9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        jMenu1.setBackground(new java.awt.Color(204, 204, 255));
        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem8.setText("Login");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem9.setText("Item List");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem10.setText("Cake");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem11.setText("Drinks");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem12.setText("Fried");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem13.setText("Pizza");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem14.setText("Soup");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem15.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem15.setText("Exit");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);

        jMenuBar1.add(jMenu1);

        jMenu3.setBackground(new java.awt.Color(204, 204, 255));
        jMenu3.setText("Theme");
        jMenu3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem1.setText("Black");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem2.setText("Blue");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem3.setText("Cyan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem4.setText("Green");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem5.setText("Orange");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem6.setText("Red");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem7.setText("White");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/cake/blackforest.jpg")));
    }//GEN-LAST:event_blackActionPerformed

    private void blueberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueberryActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/cake/blueberry.jpg")));
    }//GEN-LAST:event_blueberryActionPerformed

    private void cappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappuccinoActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/cake/cappuccino.jpg")));
    }//GEN-LAST:event_cappuccinoActionPerformed

    private void maltedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maltedActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/cake/malted.jpg")));
    }//GEN-LAST:event_maltedActionPerformed

    private void almondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almondActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/cake/almond.jpg")));
    }//GEN-LAST:event_almondActionPerformed

    private void velvetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velvetActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/cake/redvelvet.jpg")));
    }//GEN-LAST:event_velvetActionPerformed

    private void strawberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/cake/strawberry.jpg")));
    }//GEN-LAST:event_strawberryActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(this, "Confirm to Exit",  "EXIT", JOptionPane.YES_NO_OPTION);
        if (opt == 0)
        System.exit(0);

        else
        {
        }
    }//GEN-LAST:event_exitActionPerformed

    private void vanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vanillaActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/cake/vanilla.jpg")));
    }//GEN-LAST:event_vanillaActionPerformed

    private void dessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessertActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/cake/dessert.jpg")));
    }//GEN-LAST:event_dessertActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new Cake().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new Drinks().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new Fried().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        new Pizza().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        new Soup().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.BLACK);
        
        black.setBackground(Color.BLACK);
        blueberry.setBackground(Color.BLACK);
        cappuccino.setBackground(Color.BLACK);
        dessert.setBackground(Color.BLACK);
        malted.setBackground(Color.BLACK);
        almond.setBackground(Color.BLACK);
        velvet.setBackground(Color.BLACK);
        strawberry.setBackground(Color.BLACK);
        vanilla.setBackground(Color.BLACK);
        menu.setBackground(Color.BLACK);
        exit.setBackground(Color.BLACK);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.BLUE);
        
        black.setBackground(Color.BLUE);
        blueberry.setBackground(Color.BLUE);
        cappuccino.setBackground(Color.BLUE);
        dessert.setBackground(Color.BLUE);
        malted.setBackground(Color.BLUE);
        almond.setBackground(Color.BLUE);
        velvet.setBackground(Color.BLUE);
        strawberry.setBackground(Color.BLUE);
        vanilla.setBackground(Color.BLUE);
        menu.setBackground(Color.BLUE);
        exit.setBackground(Color.BLUE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.CYAN);
        
        black.setBackground(Color.CYAN);
        blueberry.setBackground(Color.CYAN);
        cappuccino.setBackground(Color.CYAN);
        dessert.setBackground(Color.CYAN);
        malted.setBackground(Color.CYAN);
        almond.setBackground(Color.CYAN);
        velvet.setBackground(Color.CYAN);
        strawberry.setBackground(Color.CYAN);
        vanilla.setBackground(Color.CYAN);
        menu.setBackground(Color.CYAN);
        exit.setBackground(Color.CYAN);
        
        black.setForeground(Color.BLACK);
        blueberry.setForeground(Color.BLACK);
        cappuccino.setForeground(Color.BLACK);
        dessert.setForeground(Color.BLACK);
        malted.setForeground(Color.BLACK);
        almond.setForeground(Color.BLACK);
        velvet.setForeground(Color.BLACK);
        strawberry.setForeground(Color.BLACK);
        vanilla.setForeground(Color.BLACK);
        menu.setForeground(Color.BLACK);
        exit.setForeground(Color.BLACK);
        
        rate.setForeground(Color.BLACK);
        rate1.setForeground(Color.BLACK);
        rate2.setForeground(Color.BLACK);
        rate3.setForeground(Color.BLACK);
        rate4.setForeground(Color.BLACK);
        rate5.setForeground(Color.BLACK);
        rate6.setForeground(Color.BLACK);
        rate7.setForeground(Color.BLACK);
        rate8.setForeground(Color.BLACK);
        rate9.setForeground(Color.BLACK);
        image.setForeground(Color.BLACK);
        title.setForeground(Color.BLACK);
        menu.setForeground(Color.BLACK);
        exit.setForeground(Color.BLACK);
        item.setForeground(Color.BLACK);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.GREEN);
        
        black.setBackground(Color.GREEN);
        blueberry.setBackground(Color.GREEN);
        cappuccino.setBackground(Color.GREEN);
        dessert.setBackground(Color.GREEN);
        malted.setBackground(Color.GREEN);
        almond.setBackground(Color.GREEN);
        velvet.setBackground(Color.GREEN);
        strawberry.setBackground(Color.GREEN);
        vanilla.setBackground(Color.GREEN);
        menu.setBackground(Color.GREEN);
        exit.setBackground(Color.GREEN);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.ORANGE);
        
        black.setBackground(Color.ORANGE);
        blueberry.setBackground(Color.ORANGE);
        cappuccino.setBackground(Color.ORANGE);
        dessert.setBackground(Color.ORANGE);
        malted.setBackground(Color.ORANGE);
        almond.setBackground(Color.ORANGE);
        velvet.setBackground(Color.ORANGE);
        strawberry.setBackground(Color.ORANGE);
        vanilla.setBackground(Color.ORANGE);
        menu.setBackground(Color.ORANGE);
        exit.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.RED);
        
        black.setBackground(Color.RED);
        blueberry.setBackground(Color.RED);
        cappuccino.setBackground(Color.RED);
        dessert.setBackground(Color.RED);
        malted.setBackground(Color.RED);
        almond.setBackground(Color.RED);
        velvet.setBackground(Color.RED);
        strawberry.setBackground(Color.RED);
        vanilla.setBackground(Color.RED);
        menu.setBackground(Color.RED);
        exit.setBackground(Color.RED);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.WHITE);
        
        black.setBackground(Color.WHITE);
        blueberry.setBackground(Color.WHITE);
        cappuccino.setBackground(Color.WHITE);
        dessert.setBackground(Color.WHITE);
        malted.setBackground(Color.WHITE);
        almond.setBackground(Color.WHITE);
        velvet.setBackground(Color.WHITE);
        strawberry.setBackground(Color.WHITE);
        vanilla.setBackground(Color.WHITE);
        menu.setBackground(Color.WHITE);
        exit.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLevel;
    private javax.swing.JButton almond;
    private javax.swing.JButton black;
    private javax.swing.JButton blueberry;
    private javax.swing.JButton cappuccino;
    private javax.swing.JButton dessert;
    private javax.swing.JButton exit;
    private javax.swing.JLabel image;
    private javax.swing.JLabel item;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton malted;
    private javax.swing.JButton menu;
    private javax.swing.JLabel rate;
    private javax.swing.JLabel rate1;
    private javax.swing.JLabel rate2;
    private javax.swing.JLabel rate3;
    private javax.swing.JLabel rate4;
    private javax.swing.JLabel rate5;
    private javax.swing.JLabel rate6;
    private javax.swing.JLabel rate7;
    private javax.swing.JLabel rate8;
    private javax.swing.JLabel rate9;
    private javax.swing.JButton strawberry;
    private javax.swing.JLabel title;
    private javax.swing.JButton vanilla;
    private javax.swing.JButton velvet;
    // End of variables declaration//GEN-END:variables
}
