import java.awt.Color;
import javax.swing.JOptionPane;

public class Drinks extends javax.swing.JFrame {

    /**
     * Creates new form Drinks
     */
    public Drinks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        item = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        coffee = new javax.swing.JButton();
        fruit = new javax.swing.JButton();
        limes = new javax.swing.JButton();
        water = new javax.swing.JButton();
        scoop = new javax.swing.JButton();
        soft = new javax.swing.JButton();
        rate6 = new javax.swing.JLabel();
        rate5 = new javax.swing.JLabel();
        rate4 = new javax.swing.JLabel();
        rate3 = new javax.swing.JLabel();
        rate2 = new javax.swing.JLabel();
        rate1 = new javax.swing.JLabel();
        ImageLevel = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        tea = new javax.swing.JButton();
        lassi = new javax.swing.JButton();
        rate7 = new javax.swing.JLabel();
        rate8 = new javax.swing.JLabel();
        tamarind = new javax.swing.JButton();
        rate9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DRINKS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));

        title.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("DRINKS");
        title.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        item.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        item.setForeground(new java.awt.Color(255, 255, 255));
        item.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        item.setText("Item List");
        item.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate.setForeground(new java.awt.Color(255, 255, 255));
        rate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate.setText("Rate");
        rate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        image.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        image.setForeground(new java.awt.Color(255, 255, 255));
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setText("Image");
        image.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        coffee.setBackground(new java.awt.Color(255, 102, 102));
        coffee.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        coffee.setForeground(new java.awt.Color(255, 255, 255));
        coffee.setText(" 1. Cold Coffee");
        coffee.setBorder(null);
        coffee.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeActionPerformed(evt);
            }
        });

        fruit.setBackground(new java.awt.Color(255, 102, 102));
        fruit.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        fruit.setForeground(new java.awt.Color(255, 255, 255));
        fruit.setText(" 2. Fruit Juice");
        fruit.setBorder(null);
        fruit.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        fruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitActionPerformed(evt);
            }
        });

        limes.setBackground(new java.awt.Color(255, 102, 102));
        limes.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        limes.setForeground(new java.awt.Color(255, 255, 255));
        limes.setText(" 4. Lemonade Limes");
        limes.setBorder(null);
        limes.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        limes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limesActionPerformed(evt);
            }
        });

        water.setBackground(new java.awt.Color(255, 102, 102));
        water.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        water.setForeground(new java.awt.Color(255, 255, 255));
        water.setText(" 5. Mineral Water");
        water.setBorder(null);
        water.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        water.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterActionPerformed(evt);
            }
        });

        scoop.setBackground(new java.awt.Color(255, 102, 102));
        scoop.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        scoop.setForeground(new java.awt.Color(255, 255, 255));
        scoop.setText(" 6. Scoop Ice-cream");
        scoop.setBorder(null);
        scoop.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        scoop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoopActionPerformed(evt);
            }
        });

        soft.setBackground(new java.awt.Color(255, 102, 102));
        soft.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        soft.setForeground(new java.awt.Color(255, 255, 255));
        soft.setText(" 7. Soft Cold Drinks");
        soft.setBorder(null);
        soft.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        soft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                softActionPerformed(evt);
            }
        });

        rate6.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate6.setForeground(new java.awt.Color(255, 255, 255));
        rate6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate6.setText("275/-");
        rate6.setToolTipText("");
        rate6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate5.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate5.setForeground(new java.awt.Color(255, 255, 255));
        rate5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate5.setText("60/-");
        rate5.setToolTipText("");
        rate5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate4.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate4.setForeground(new java.awt.Color(255, 255, 255));
        rate4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate4.setText("90/-");
        rate4.setToolTipText("");
        rate4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate3.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate3.setForeground(new java.awt.Color(255, 255, 255));
        rate3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate3.setText("100/-");
        rate3.setToolTipText("");
        rate3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate2.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate2.setForeground(new java.awt.Color(255, 255, 255));
        rate2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate2.setText("120/-");
        rate2.setToolTipText("");
        rate2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate1.setForeground(new java.awt.Color(255, 255, 255));
        rate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate1.setText("175/-");
        rate1.setToolTipText("");
        rate1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        menu.setBackground(new java.awt.Color(255, 102, 102));
        menu.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 102, 102));
        exit.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        tea.setBackground(new java.awt.Color(255, 102, 102));
        tea.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        tea.setForeground(new java.awt.Color(255, 255, 255));
        tea.setText(" 9. Tea");
        tea.setBorder(null);
        tea.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaActionPerformed(evt);
            }
        });

        lassi.setBackground(new java.awt.Color(255, 102, 102));
        lassi.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        lassi.setForeground(new java.awt.Color(255, 255, 255));
        lassi.setText(" 3. Lassi");
        lassi.setBorder(null);
        lassi.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        lassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lassiActionPerformed(evt);
            }
        });

        rate7.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate7.setForeground(new java.awt.Color(255, 255, 255));
        rate7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate7.setText("150/-");
        rate7.setToolTipText("");
        rate7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        rate8.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate8.setForeground(new java.awt.Color(255, 255, 255));
        rate8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate8.setText("110/-");
        rate8.setToolTipText("");
        rate8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        tamarind.setBackground(new java.awt.Color(255, 102, 102));
        tamarind.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        tamarind.setForeground(new java.awt.Color(255, 255, 255));
        tamarind.setText(" 8. Tamarind Juice");
        tamarind.setBorder(null);
        tamarind.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        tamarind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamarindActionPerformed(evt);
            }
        });

        rate9.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rate9.setForeground(new java.awt.Color(255, 255, 255));
        rate9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate9.setText("70/-");
        rate9.setToolTipText("");
        rate9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(coffee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fruit, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(limes, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(water, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scoop, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(soft, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tea, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tamarind, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lassi, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ImageLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item)
                    .addComponent(rate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(image))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ImageLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rate2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rate3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rate4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rate5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rate6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rate7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rate8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rate9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(coffee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fruit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lassi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(water, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scoop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(soft, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tamarind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        jMenu1.setBackground(new java.awt.Color(204, 204, 255));
        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem8.setText("Login");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem9.setText("Item List");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem10.setText("Cake");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem11.setText("Drinks");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem12.setText("Fried");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem13.setText("Pizza");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem14.setText("Soup");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem15.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem15.setText("Exit");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);

        jMenuBar1.add(jMenu1);

        jMenu3.setBackground(new java.awt.Color(204, 204, 255));
        jMenu3.setText("Theme");
        jMenu3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem1.setText("Black");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem2.setText("Blue");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem3.setText("Cyan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem4.setText("Green");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem5.setText("Orange");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem6.setText("Red");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem7.setText("White");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeeActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/drinks/coffee.jpg")));
    }//GEN-LAST:event_coffeeActionPerformed

    private void fruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/drinks/fruit.jpg")));
    }//GEN-LAST:event_fruitActionPerformed

    private void limesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limesActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/drinks/lemon.jpg")));
    }//GEN-LAST:event_limesActionPerformed

    private void waterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/drinks/water.jpg")));
    }//GEN-LAST:event_waterActionPerformed

    private void scoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoopActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/drinks/scoop.jpg")));
    }//GEN-LAST:event_scoopActionPerformed

    private void softActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_softActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/drinks/drink.jpg")));
    }//GEN-LAST:event_softActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(this, "Confirm to Exit",  "EXIT", JOptionPane.YES_NO_OPTION);
        if (opt == 0)
        System.exit(0);

        else
        {
        }
    }//GEN-LAST:event_exitActionPerformed

    private void teaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/drinks/tea.jpg")));
    }//GEN-LAST:event_teaActionPerformed

    private void lassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lassiActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/drinks/lassi.jpg")));
    }//GEN-LAST:event_lassiActionPerformed

    private void tamarindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamarindActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/drinks/tamarind.jpg")));
    }//GEN-LAST:event_tamarindActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new Cake().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new Drinks().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new Fried().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        new Pizza().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        new Soup().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.BLACK);
        
        coffee.setBackground(Color.BLACK);
        fruit.setBackground(Color.BLACK);
        lassi.setBackground(Color.BLACK);
        limes.setBackground(Color.BLACK);
        water.setBackground(Color.BLACK);
        scoop.setBackground(Color.BLACK);
        soft.setBackground(Color.BLACK);
        tamarind.setBackground(Color.BLACK);
        tea.setBackground(Color.BLACK);
        menu.setBackground(Color.BLACK);
        exit.setBackground(Color.BLACK);
        
        coffee.setForeground(Color.WHITE);
        fruit.setForeground(Color.WHITE);
        lassi.setForeground(Color.WHITE);
        limes.setForeground(Color.WHITE);
        water.setForeground(Color.WHITE);
        scoop.setForeground(Color.WHITE);
        soft.setForeground(Color.WHITE);
        tamarind.setForeground(Color.WHITE);
        tea.setForeground(Color.WHITE);
        menu.setForeground(Color.WHITE);
        exit.setForeground(Color.WHITE);
        
        title.setForeground(Color.WHITE);
        item.setForeground(Color.WHITE);
        rate.setForeground(Color.WHITE);
        image.setForeground(Color.WHITE);
        rate1.setForeground(Color.WHITE);
        rate2.setForeground(Color.WHITE);
        rate3.setForeground(Color.WHITE);
        rate4.setForeground(Color.WHITE);
        rate5.setForeground(Color.WHITE);
        rate6.setForeground(Color.WHITE);
        rate7.setForeground(Color.WHITE);
        rate8.setForeground(Color.WHITE);
        rate9.setForeground(Color.WHITE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.BLUE);
        
        coffee.setBackground(Color.BLUE);
        fruit.setBackground(Color.BLUE);
        lassi.setBackground(Color.BLUE);
        limes.setBackground(Color.BLUE);
        water.setBackground(Color.BLUE);
        scoop.setBackground(Color.BLUE);
        soft.setBackground(Color.BLUE);
        tamarind.setBackground(Color.BLUE);
        tea.setBackground(Color.BLUE);
        menu.setBackground(Color.BLUE);
        exit.setBackground(Color.BLUE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.CYAN);
        
        coffee.setBackground(Color.CYAN);
        fruit.setBackground(Color.CYAN);
        lassi.setBackground(Color.CYAN);
        limes.setBackground(Color.CYAN);
        water.setBackground(Color.CYAN);
        scoop.setBackground(Color.CYAN);
        soft.setBackground(Color.CYAN);
        tamarind.setBackground(Color.CYAN);
        tea.setBackground(Color.CYAN);
        menu.setBackground(Color.CYAN);
        exit.setBackground(Color.CYAN);
        
        coffee.setForeground(Color.BLACK);
        fruit.setForeground(Color.BLACK);
        lassi.setForeground(Color.BLACK);
        limes.setForeground(Color.BLACK);
        water.setForeground(Color.BLACK);
        scoop.setForeground(Color.BLACK);
        soft.setForeground(Color.BLACK);
        tamarind.setForeground(Color.BLACK);
        tea.setForeground(Color.BLACK);
        menu.setForeground(Color.BLACK);
        exit.setForeground(Color.BLACK);
        
        title.setForeground(Color.BLACK);
        item.setForeground(Color.BLACK);
        rate.setForeground(Color.BLACK);
        image.setForeground(Color.BLACK);
        rate1.setForeground(Color.BLACK);
        rate2.setForeground(Color.BLACK);
        rate3.setForeground(Color.BLACK);
        rate4.setForeground(Color.BLACK);
        rate5.setForeground(Color.BLACK);
        rate6.setForeground(Color.BLACK);
        rate7.setForeground(Color.BLACK);
        rate8.setForeground(Color.BLACK);
        rate9.setForeground(Color.BLACK);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.GREEN);
        
        coffee.setBackground(Color.GREEN);
        fruit.setBackground(Color.GREEN);
        lassi.setBackground(Color.GREEN);
        limes.setBackground(Color.GREEN);
        water.setBackground(Color.GREEN);
        scoop.setBackground(Color.GREEN);
        soft.setBackground(Color.GREEN);
        tamarind.setBackground(Color.GREEN);
        tea.setBackground(Color.GREEN);
        menu.setBackground(Color.GREEN);
        exit.setBackground(Color.GREEN);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.RED);
        
        coffee.setBackground(Color.RED);
        fruit.setBackground(Color.RED);
        lassi.setBackground(Color.RED);
        limes.setBackground(Color.RED);
        water.setBackground(Color.RED);
        scoop.setBackground(Color.RED);
        soft.setBackground(Color.RED);
        tamarind.setBackground(Color.RED);
        tea.setBackground(Color.RED);
        menu.setBackground(Color.RED);
        exit.setBackground(Color.RED);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.WHITE);
        
        coffee.setBackground(Color.WHITE);
        fruit.setBackground(Color.WHITE);
        lassi.setBackground(Color.WHITE);
        limes.setBackground(Color.WHITE);
        water.setBackground(Color.WHITE);
        scoop.setBackground(Color.WHITE);
        soft.setBackground(Color.WHITE);
        tamarind.setBackground(Color.WHITE);
        tea.setBackground(Color.WHITE);
        menu.setBackground(Color.WHITE);
        exit.setBackground(Color.WHITE);
        
        coffee.setForeground(Color.BLACK);
        fruit.setForeground(Color.BLACK);
        lassi.setForeground(Color.BLACK);
        limes.setForeground(Color.BLACK);
        water.setForeground(Color.BLACK);
        scoop.setForeground(Color.BLACK);
        soft.setForeground(Color.BLACK);
        tamarind.setForeground(Color.BLACK);
        tea.setForeground(Color.BLACK);
        
        title.setForeground(Color.BLACK);
        item.setForeground(Color.BLACK);
        rate.setForeground(Color.BLACK);
        image.setForeground(Color.BLACK);
        rate1.setForeground(Color.BLACK);
        rate2.setForeground(Color.BLACK);
        rate3.setForeground(Color.BLACK);
        rate4.setForeground(Color.BLACK);
        rate5.setForeground(Color.BLACK);
        rate6.setForeground(Color.BLACK);
        rate7.setForeground(Color.BLACK);
        rate8.setForeground(Color.BLACK);
        rate9.setForeground(Color.BLACK);
        menu.setForeground(Color.BLACK);
        exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drinks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLevel;
    private javax.swing.JButton coffee;
    private javax.swing.JButton exit;
    private javax.swing.JButton fruit;
    private javax.swing.JLabel image;
    private javax.swing.JLabel item;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lassi;
    private javax.swing.JButton limes;
    private javax.swing.JButton menu;
    private javax.swing.JLabel rate;
    private javax.swing.JLabel rate1;
    private javax.swing.JLabel rate2;
    private javax.swing.JLabel rate3;
    private javax.swing.JLabel rate4;
    private javax.swing.JLabel rate5;
    private javax.swing.JLabel rate6;
    private javax.swing.JLabel rate7;
    private javax.swing.JLabel rate8;
    private javax.swing.JLabel rate9;
    private javax.swing.JButton scoop;
    private javax.swing.JButton soft;
    private javax.swing.JButton tamarind;
    private javax.swing.JButton tea;
    private javax.swing.JLabel title;
    private javax.swing.JButton water;
    // End of variables declaration//GEN-END:variables
}
