
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.awt.*;

public class Pizza extends javax.swing.JFrame {

    /**
     * Creates new form Pizza
     */
    public Pizza() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        i = new javax.swing.JLabel();
        cp = new javax.swing.JButton();
        pp = new javax.swing.JButton();
        ct = new javax.swing.JButton();
        gcp = new javax.swing.JButton();
        rg = new javax.swing.JButton();
        vs = new javax.swing.JButton();
        zs = new javax.swing.JButton();
        p8 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        ImageLevel = new javax.swing.JLabel();
        m = new javax.swing.JButton();
        gc = new javax.swing.JButton();
        p9 = new javax.swing.JLabel();
        po = new javax.swing.JButton();
        p6 = new javax.swing.JLabel();
        e = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PIZZA");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));

        t.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        t.setForeground(new java.awt.Color(51, 255, 0));
        t.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t.setText("PIZZA");
        t.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        l.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        l.setForeground(new java.awt.Color(51, 255, 0));
        l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l.setText("Item List");
        l.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        p.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        p.setForeground(new java.awt.Color(51, 255, 0));
        p.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p.setText("Rate");
        p.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        i.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        i.setForeground(new java.awt.Color(51, 255, 0));
        i.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i.setText("Image");
        i.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        cp.setBackground(new java.awt.Color(102, 0, 153));
        cp.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        cp.setForeground(new java.awt.Color(51, 255, 0));
        cp.setText(" 1. BBQ Chicken Pizza");
        cp.setBorder(null);
        cp.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        cp.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpActionPerformed(evt);
            }
        });

        pp.setBackground(new java.awt.Color(102, 0, 153));
        pp.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        pp.setForeground(new java.awt.Color(51, 255, 0));
        pp.setText(" 2. Beef Pepperoni Pizza");
        pp.setBorder(null);
        pp.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppActionPerformed(evt);
            }
        });

        ct.setBackground(new java.awt.Color(102, 0, 153));
        ct.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        ct.setForeground(new java.awt.Color(51, 255, 0));
        ct.setText(" 3. Chicken Tandoori Pizza");
        ct.setBorder(null);
        ct.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctActionPerformed(evt);
            }
        });

        gcp.setBackground(new java.awt.Color(102, 0, 153));
        gcp.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        gcp.setForeground(new java.awt.Color(51, 255, 0));
        gcp.setText(" 5. Grilled Chicken Pizza");
        gcp.setBorder(null);
        gcp.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        gcp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcpActionPerformed(evt);
            }
        });

        rg.setBackground(new java.awt.Color(102, 0, 153));
        rg.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        rg.setForeground(new java.awt.Color(51, 255, 0));
        rg.setText(" 7. Roasted Garlic Pizza");
        rg.setBorder(null);
        rg.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgActionPerformed(evt);
            }
        });

        vs.setBackground(new java.awt.Color(102, 0, 153));
        vs.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        vs.setForeground(new java.awt.Color(51, 255, 0));
        vs.setText(" 8. Veggie Supreme Pizza");
        vs.setBorder(null);
        vs.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        vs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsActionPerformed(evt);
            }
        });

        zs.setBackground(new java.awt.Color(102, 0, 153));
        zs.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        zs.setForeground(new java.awt.Color(51, 255, 0));
        zs.setText(" 9. Zesty Spicy Pizza");
        zs.setBorder(null);
        zs.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        zs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zsActionPerformed(evt);
            }
        });

        p8.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        p8.setForeground(new java.awt.Color(51, 255, 0));
        p8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p8.setText("575/-");
        p8.setToolTipText("");
        p8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        p7.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        p7.setForeground(new java.awt.Color(51, 255, 0));
        p7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p7.setText("650/-");
        p7.setToolTipText("");
        p7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        p5.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        p5.setForeground(new java.awt.Color(51, 255, 0));
        p5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p5.setText("725/-");
        p5.setToolTipText("");
        p5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        p4.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        p4.setForeground(new java.awt.Color(51, 255, 0));
        p4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p4.setText("750/-");
        p4.setToolTipText("");
        p4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        p3.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        p3.setForeground(new java.awt.Color(51, 255, 0));
        p3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p3.setText("600/-");
        p3.setToolTipText("");
        p3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        p2.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        p2.setForeground(new java.awt.Color(51, 255, 0));
        p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2.setText("675/-");
        p2.setToolTipText("");
        p2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        p1.setBackground(new java.awt.Color(153, 153, 255));
        p1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        p1.setForeground(new java.awt.Color(51, 255, 0));
        p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1.setText("650/-");
        p1.setToolTipText("");
        p1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        m.setBackground(new java.awt.Color(102, 0, 153));
        m.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        m.setForeground(new java.awt.Color(51, 255, 0));
        m.setText("MENU");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        gc.setBackground(new java.awt.Color(102, 0, 153));
        gc.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        gc.setForeground(new java.awt.Color(51, 255, 0));
        gc.setText(" 4. Gorgonzola Cheese Pizza");
        gc.setBorder(null);
        gc.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        gc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcActionPerformed(evt);
            }
        });

        p9.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        p9.setForeground(new java.awt.Color(51, 255, 0));
        p9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p9.setText("700/-");
        p9.setToolTipText("");
        p9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        po.setBackground(new java.awt.Color(102, 0, 153));
        po.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        po.setForeground(new java.awt.Color(51, 255, 0));
        po.setText(" 6. Pizza Ortolana");
        po.setBorder(null);
        po.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        po.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poActionPerformed(evt);
            }
        });

        p6.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        p6.setForeground(new java.awt.Color(51, 255, 0));
        p6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p6.setText("720/-");
        p6.setToolTipText("");
        p6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        e.setBackground(new java.awt.Color(102, 0, 153));
        e.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        e.setForeground(new java.awt.Color(51, 255, 0));
        e.setText("EXIT");
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(337, 337, 337))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(po, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ct, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gcp, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vs, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zs, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(gc, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ImageLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(i, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l)
                    .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(i, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gcp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(po, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ImageLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        jMenu1.setBackground(new java.awt.Color(204, 204, 255));
        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem8.setText("Login");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem9.setText("Item List");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem10.setText("Cake");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem11.setText("Drinks");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem12.setText("Fried");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem13.setText("Pizza");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem14.setText("Soup");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem15.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem15.setText("Exit");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);

        jMenuBar1.add(jMenu1);

        jMenu3.setBackground(new java.awt.Color(204, 204, 255));
        jMenu3.setText("Theme");
        jMenu3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem1.setText("Black");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem2.setText("Blue");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem3.setText("Cyan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem4.setText("Green");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem5.setText("Orange");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem6.setText("Red");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem7.setText("White");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/pizza/bbq.jpg")));
    }//GEN-LAST:event_cpActionPerformed

    private void ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/pizza/beef.jpg")));
    }//GEN-LAST:event_ppActionPerformed

    private void ctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/pizza/tandoori.jpg")));
    }//GEN-LAST:event_ctActionPerformed

    private void gcpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcpActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/pizza/grilled.jpg")));
    }//GEN-LAST:event_gcpActionPerformed

    private void rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/pizza/roasted.jpg")));
    }//GEN-LAST:event_rgActionPerformed

    private void vsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/pizza/veggie.jpg")));
    }//GEN-LAST:event_vsActionPerformed

    private void zsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zsActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/pizza/zesty.jpg")));
    }//GEN-LAST:event_zsActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_mActionPerformed

    private void gcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/pizza/gorgonzola.jpg")));
    }//GEN-LAST:event_gcActionPerformed

    private void poActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poActionPerformed
        // TODO add your handling code here:
        ImageLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/pizza/ortolana.jpg")));
    }//GEN-LAST:event_poActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(this, "Confirm to Exit",  "EXIT", JOptionPane.YES_NO_OPTION);
        if (opt == 0)
        System.exit(0);
        
        else
        {            
        }
    }//GEN-LAST:event_eActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new Cake().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new Drinks().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new Fried().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        new Pizza().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        new Soup().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.BLACK);
        
        cp.setBackground(Color.BLACK);
        pp.setBackground(Color.BLACK);
        ct.setBackground(Color.BLACK);
        gc.setBackground(Color.BLACK);
        gcp.setBackground(Color.BLACK);
        po.setBackground(Color.BLACK);
        rg.setBackground(Color.BLACK);
        vs.setBackground(Color.BLACK);
        zs.setBackground(Color.BLACK);
        m.setBackground(Color.BLACK);
        e.setBackground(Color.BLACK);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.BLUE);
        
        cp.setBackground(Color.BLUE);
        pp.setBackground(Color.BLUE);
        ct.setBackground(Color.BLUE);
        gc.setBackground(Color.BLUE);
        gcp.setBackground(Color.BLUE);
        po.setBackground(Color.BLUE);
        rg.setBackground(Color.BLUE);
        vs.setBackground(Color.BLUE);
        zs.setBackground(Color.BLUE);
        m.setBackground(Color.BLUE);
        e.setBackground(Color.BLUE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.CYAN);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.GREEN);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.ORANGE);
        
        cp.setBackground(Color.ORANGE);
        pp.setBackground(Color.ORANGE);
        ct.setBackground(Color.ORANGE);
        gc.setBackground(Color.ORANGE);
        gcp.setBackground(Color.ORANGE);
        po.setBackground(Color.ORANGE);
        rg.setBackground(Color.ORANGE);
        vs.setBackground(Color.ORANGE);
        zs.setBackground(Color.ORANGE);
        m.setBackground(Color.ORANGE);
        e.setBackground(Color.ORANGE);
        
        cp.setForeground(Color.BLACK);
        pp.setForeground(Color.BLACK);
        ct.setForeground(Color.BLACK);
        gc.setForeground(Color.BLACK);
        gcp.setForeground(Color.BLACK);
        po.setForeground(Color.BLACK);
        rg.setForeground(Color.BLACK);
        vs.setForeground(Color.BLACK);
        zs.setForeground(Color.BLACK);
        m.setForeground(Color.BLACK);
        e.setForeground(Color.BLACK);
        
        p.setForeground(Color.BLACK);
        p1.setForeground(Color.BLACK);
        p2.setForeground(Color.BLACK);
        p3.setForeground(Color.BLACK);
        p4.setForeground(Color.BLACK);
        p5.setForeground(Color.BLACK);
        p6.setForeground(Color.BLACK);
        p7.setForeground(Color.BLACK);
        p8.setForeground(Color.BLACK);
        p9.setForeground(Color.BLACK);
        t.setForeground(Color.BLACK);
        i.setForeground(Color.BLACK);
        l.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.RED);
        
        cp.setBackground(Color.RED);
        pp.setBackground(Color.RED);
        ct.setBackground(Color.RED);
        gc.setBackground(Color.RED);
        gcp.setBackground(Color.RED);
        po.setBackground(Color.RED);
        rg.setBackground(Color.RED);
        vs.setBackground(Color.RED);
        zs.setBackground(Color.RED);
        m.setBackground(Color.RED);
        e.setBackground(Color.RED);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.WHITE);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLevel;
    private javax.swing.JButton cp;
    private javax.swing.JButton ct;
    private javax.swing.JButton e;
    private javax.swing.JButton gc;
    private javax.swing.JButton gcp;
    private javax.swing.JLabel i;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l;
    private javax.swing.JButton m;
    private javax.swing.JLabel p;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel p9;
    private javax.swing.JButton po;
    private javax.swing.JButton pp;
    private javax.swing.JButton rg;
    private javax.swing.JLabel t;
    private javax.swing.JButton vs;
    private javax.swing.JButton zs;
    // End of variables declaration//GEN-END:variables
}
