
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Monija
 */
public class Payment extends javax.swing.JFrame {

    
    double [] i = new double [50];
    
    double [] cake = new double [10];
    double [] drink = new double [10];
    double [] fried = new double [10];
    double [] pizza = new double [10];
    double [] soup = new double [10];
    double [] cost = new double [4];
    
    
    
    
    
    
    
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c = new javax.swing.JRadioButton();
        d = new javax.swing.JRadioButton();
        m = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        v = new javax.swing.JRadioButton();
        card = new javax.swing.JRadioButton();
        cash = new javax.swing.JTextField();
        Card = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAYMENT");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel3.setText("BDT");

        buttonGroup2.add(c);
        c.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        c.setText("Credit Card");

        buttonGroup2.add(d);
        d.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        d.setText("Debit Card");

        buttonGroup2.add(m);
        m.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        m.setText("Master Card");

        jButton1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jRadioButton1.setText("CASH    :");

        buttonGroup2.add(v);
        v.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        v.setText("Visa Card");

        buttonGroup1.add(card);
        card.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        card.setText("CARD   :");
        card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardMouseClicked(evt);
            }
        });
        card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardActionPerformed(evt);
            }
        });

        cash.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        cash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cash.setText("0");

        Card.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        Card.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Card.setText("0");

        jLabel2.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel2.setText("BDT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Card, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(204, 204, 204))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Card, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 0));

        jMenu1.setBackground(new java.awt.Color(204, 204, 255));
        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem8.setText("Login");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem9.setText("Item List");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem10.setText("Cake");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem11.setText("Drinks");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem12.setText("Fried");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem13.setText("Pizza");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem14.setText("Soup");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem15.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem15.setText("Exit");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);

        jMenuBar1.add(jMenu1);

        jMenu3.setBackground(new java.awt.Color(204, 204, 255));
        jMenu3.setText("Theme");
        jMenu3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem1.setText("Black");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem2.setText("Blue");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem3.setText("Cyan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem4.setText("Green");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem5.setText("Orange");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem6.setText("Red");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jMenuItem7.setText("White");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
            cake[0] = Double.parseDouble(Order.black.getText());
            cake[1] = Double.parseDouble(Order.blueberry.getText());
            cake[2] = Double.parseDouble(Order.cappuccino.getText());
            cake[3] = Double.parseDouble(Order.dessert.getText());
            cake[4] = Double.parseDouble(Order.malted.getText());
            cake[5] = Double.parseDouble(Order.almond.getText());
            cake[6] = Double.parseDouble(Order.velvet.getText());
            cake[7] = Double.parseDouble(Order.strawberry.getText());
            cake[8] = Double.parseDouble(Order.vanilla.getText());
            cake[9] = Double.parseDouble(Order.cake_total.getText());

            drink[0] = Double.parseDouble(Order.coffee.getText());
            drink[1] = Double.parseDouble(Order.fruit.getText());
            drink[2] = Double.parseDouble(Order.lassi.getText());
            drink[3] = Double.parseDouble(Order.limes.getText());
            drink[4] = Double.parseDouble(Order.water.getText());
            drink[5] = Double.parseDouble(Order.scoop.getText());
            drink[6] = Double.parseDouble(Order.soft.getText());
            drink[7] = Double.parseDouble(Order.tamarind.getText());
            drink[8] = Double.parseDouble(Order.tea.getText());
            drink[9] = Double.parseDouble(Order.drinks_total.getText());

            fried[0] = Double.parseDouble(Order.bbq_fried.getText());
            fried[1] = Double.parseDouble(Order.beef_cheese.getText());
            fried[2] = Double.parseDouble(Order.steak.getText());
            fried[3] = Double.parseDouble(Order.beef_sandwich.getText());
            fried[4] = Double.parseDouble(Order.chicken_burger.getText());
            fried[5] = Double.parseDouble(Order.chicken_sandwich.getText());
            fried[6] = Double.parseDouble(Order.grilled_chicken.getText());
            fried[7] = Double.parseDouble(Order.pasta.getText());
            fried[8] = Double.parseDouble(Order.shrimp.getText());
            fried[9] = Double.parseDouble(Order.fried_total.getText());

            pizza[0] = Double.parseDouble(Order.bbq_pizza.getText());
            pizza[1] = Double.parseDouble(Order.beef_pepperoni.getText());
            pizza[2] = Double.parseDouble(Order.tandoori.getText());
            pizza[3] = Double.parseDouble(Order.gorgonzola.getText());
            pizza[4] = Double.parseDouble(Order.grilled.getText());
            pizza[5] = Double.parseDouble(Order.ortolana.getText());
            pizza[6] = Double.parseDouble(Order.roasted.getText());
            pizza[7] = Double.parseDouble(Order.veggie.getText());
            pizza[8] = Double.parseDouble(Order.zesty.getText());
            pizza[9] = Double.parseDouble(Order.pizza_total.getText());

            soup[0] = Double.parseDouble(Order.broccoli.getText());
            soup[1] = Double.parseDouble(Order.chicken_corn.getText());
            soup[2] = Double.parseDouble(Order.cream.getText());
            soup[3] = Double.parseDouble(Order.french.getText());
            soup[4] = Double.parseDouble(Order.minestrone.getText());
            soup[5] = Double.parseDouble(Order.mushroom.getText());
            soup[6] = Double.parseDouble(Order.prawn.getText());
            soup[7] = Double.parseDouble(Order.tom.getText());
            soup[8] = Double.parseDouble(Order.egg.getText());
            soup[9] = Double.parseDouble(Order.soup_total.getText());

            cost[0] = Double.parseDouble(Order.stotal.getText());
            cost[1] = Double.parseDouble(Order.vat.getText());
            cost[2] = Double.parseDouble(Order.gtotal.getText());
            cost[3] = Double.parseDouble(Order.HomeDl.getText());       
        
        
        
        
        
        
        String pre = Order.gtotal.getText();
        String CASH = cash.getText();
        String CARD = Card.getText();

        
        Double cs = Double.parseDouble(CASH);
        Double cr = Double.parseDouble(CARD);
        Double order = Double.parseDouble(pre);

       // if (pre.equals(CASH) || pre.equals(CARD))
       
       Double money1 = cs - order;
       Double money2 = cr - order;
        
        if( (cs >= order) )
                {
                    JOptionPane.showMessageDialog(this,
                            "\tGrand Total:\t" +order +
                                    "\n\tYOU Paid:\t" +cs +
                                    "\n\tMoney Back:\t" +money1, 
                            "Money Calculation", JOptionPane.PLAIN_MESSAGE);
            new Receipt().setVisible(true);
            
            

            

            //String CName = Receipt.receipt.getText();
            //CustomerName.setText(CName);
            Receipt.receipt.append("\n\t  Restaurant Management System"+
                "\n\t ==============================\n"+
                "\n     Date: "+Order.date.getText()+ "\t Time: "+Order.time.getText()+
                "\n     Customer Name: "+Order.CustomerName.getText()+
                "\n     Table NO: "+Order.TableNO.getText()+ 
                "\t Delivery Address: "+CustomerData.home.getText() +
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     Black Forest Cake          :    " +cake[0]*850+
                "\n     Blueberry Cake             :    " +cake[1]*750+
                "\n     Cappuccino Cake            :    " +cake[2]*980+
                "\n     Chocolate Dessert Cake     :    " +cake[3]*720+
                "\n     Malted Chocolate Cake      :    " +cake[4]*950+
                "\n     Pistachio Almond Cake      :    " +cake[5]*850+
                "\n     Red Velvet Cake            :    " +cake[6]*800+
                "\n     Strawberry Chocolate Cake  :    " +cake[7]*730+
                "\n     Vanilla Cake               :    " +cake[8]*900+
                "\n    ---------------------------------------" +
                "\n     CAKE Total Cost            :    " +cake[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     Cold Coffee                :    " +drink[0]*175+
                "\n     Fruit Juice                :    " +drink[1]*120+
                "\n     Lassi                      :    " +drink[2]*100+
                "\n     Lemonade Limes             :    " +drink[3]*90+
                "\n     Mineral Water              :    " +drink[4]*60+
                "\n     Scoop Ice-cream            :    " +drink[5]*275+
                "\n     Soft Cold Drinks           :    " +drink[6]*150+
                "\n     Tamarind Juice             :    " +drink[7]*110+
                "\n     Tea                        :    " +drink[8]*70+
                "\n    ---------------------------------------" +
                "\n     DRINKS Total Cost          :    " +drink[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     BBQ Chicken Wings          :    " +fried[0]*550+
                "\n     Beef Cheese Burger         :    " +fried[1]*225+
                "\n     Beef Pepper Steak          :    " +fried[2]*275+
                "\n     Beef Sandwich              :    " +fried[3]*200+
                "\n     Chicken Burge              :    " +fried[4]*250+
                "\n     Chicken Sandwich           :    " +fried[5]*225+
                "\n     Grilled Chicken            :    " +fried[6]*350+
                "\n     Seafood Pasta              :    " +fried[7]*150+
                "\n     Shrimp Sandwich            :    " +fried[8]*180+
                "\n    ---------------------------------------" +
                "\n     FRIED Total Cost           :    " +fried[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     BBQ Chicken Pizza          :    " +pizza[0]*550+
                "\n     Beef Pepperoni Pizza       :    " +pizza[1]*675+
                "\n     Chicken Tandoori Pizza     :    " +pizza[2]*600+
                "\n     Gorgozola Cheese Pizza     :    " +pizza[3]*750+
                "\n     Grilled Chicken Pizza      :    " +pizza[4]*725+
                "\n     Pizza Ortolana             :    " +pizza[5]*720+
                "\n     Roasted Garlic Pizza       :    " +pizza[6]*650+
                "\n     Veggie Supreme Pizza       :    " +pizza[7]*575+
                "\n     Zesty Spicy Pizza          :    " +pizza[8]*700+
                "\n    ---------------------------------------" +
                "\n     PIZZA Total Cost           :    " +pizza[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     Broccoli Cheese Soup       :    " +soup[0]*275+
                "\n     Chicken Corn Soup          :    " +soup[1]*250+
                "\n     Cream Pane Soup            :    " +soup[2]*175+
                "\n     French Onion Soup          :    " +soup[3]*220+
                "\n     Minestrone Soup            :    " +soup[4]*280+
                "\n     Pane Mushroom Soup         :    " +soup[5]*200+
                "\n     Prawn Corn Soup            :    " +soup[6]*300+
                "\n     Tom Yam Soup               :    " +soup[7]*350+
                "\n     Whipped Egg Soup           :    " +soup[8]*250+
                "\n    ---------------------------------------" +
                "\n     SOUP Total Cost            :    " +soup[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     Delivery Charge            :   " +cost[3]+
                "\n     Sub Total                  :   " +cost[0]+
                "\n     VAT                        :   " +cost[1]+
                "\n     GRAND TOTAL                :   " +cost[2]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n\t\t  Thank You!"+
                "\n    * * * * * * * * * * * * * * * * * * * *\n\n" );

        }
        
        else if ( cr >= order){
            
            
            JOptionPane.showMessageDialog(this,
                            "\tGrand Total:\t" +order +
                                    "\n\tYOU Paid:\t" +cr +
                                    "\n\tMoney Back:\t" +money2, 
                            "Money Calculation", JOptionPane.PLAIN_MESSAGE);
            new Receipt().setVisible(true);
                        

            

            //String CName = Receipt.receipt.getText();
            //CustomerName.setText(CName);
            Receipt.receipt.append("\n\t  Restaurant Management System"+
                "\n\t ==============================\n"+
                "\n     Date: "+Order.date.getText()+ "\t Time: "+Order.time.getText()+
                "\n     Customer Name: "+Order.CustomerName.getText()+
                "\n     Table NO: "+Order.TableNO.getText()+ 
                "\t Delivery Address: "+CustomerData.home.getText() +
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     Black Forest Cake          :    " +cake[0]*850+
                "\n     Blueberry Cake             :    " +cake[1]*750+
                "\n     Cappuccino Cake            :    " +cake[2]*980+
                "\n     Chocolate Dessert Cake     :    " +cake[3]*720+
                "\n     Malted Chocolate Cake      :    " +cake[4]*950+
                "\n     Pistachio Almond Cake      :    " +cake[5]*850+
                "\n     Red Velvet Cake            :    " +cake[6]*800+
                "\n     Strawberry Chocolate Cake  :    " +cake[7]*730+
                "\n     Vanilla Cake               :    " +cake[8]*900+
                "\n    ---------------------------------------" +
                "\n     CAKE Total Cost            :    " +cake[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     Cold Coffee                :    " +drink[0]*175+
                "\n     Fruit Juice                :    " +drink[1]*120+
                "\n     Lassi                      :    " +drink[2]*100+
                "\n     Lemonade Limes             :    " +drink[3]*90+
                "\n     Mineral Water              :    " +drink[4]*60+
                "\n     Scoop Ice-cream            :    " +drink[5]*275+
                "\n     Soft Cold Drinks           :    " +drink[6]*150+
                "\n     Tamarind Juice             :    " +drink[7]*110+
                "\n     Tea                        :    " +drink[8]*70+
                "\n    ---------------------------------------" +
                "\n     DRINKS Total Cost          :    " +drink[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     BBQ Chicken Wings          :    " +fried[0]*550+
                "\n     Beef Cheese Burger         :    " +fried[1]*225+
                "\n     Beef Pepper Steak          :    " +fried[2]*275+
                "\n     Beef Sandwich              :    " +fried[3]*200+
                "\n     Chicken Burge              :    " +fried[4]*250+
                "\n     Chicken Sandwich           :    " +fried[5]*225+
                "\n     Grilled Chicken            :    " +fried[6]*350+
                "\n     Seafood Pasta              :    " +fried[7]*150+
                "\n     Shrimp Sandwich            :    " +fried[8]*180+
                "\n    ---------------------------------------" +
                "\n     FRIED Total Cost           :    " +fried[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     BBQ Chicken Pizza          :    " +pizza[0]*550+
                "\n     Beef Pepperoni Pizza       :    " +pizza[1]*675+
                "\n     Chicken Tandoori Pizza     :    " +pizza[2]*600+
                "\n     Gorgozola Cheese Pizza     :    " +pizza[3]*750+
                "\n     Grilled Chicken Pizza      :    " +pizza[4]*725+
                "\n     Pizza Ortolana             :    " +pizza[5]*720+
                "\n     Roasted Garlic Pizza       :    " +pizza[6]*650+
                "\n     Veggie Supreme Pizza       :    " +pizza[7]*575+
                "\n     Zesty Spicy Pizza          :    " +pizza[8]*700+
                "\n    ---------------------------------------" +
                "\n     PIZZA Total Cost           :    " +pizza[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     Broccoli Cheese Soup       :    " +soup[0]*275+
                "\n     Chicken Corn Soup          :    " +soup[1]*250+
                "\n     Cream Pane Soup            :    " +soup[2]*175+
                "\n     French Onion Soup          :    " +soup[3]*220+
                "\n     Minestrone Soup            :    " +soup[4]*280+
                "\n     Pane Mushroom Soup         :    " +soup[5]*200+
                "\n     Prawn Corn Soup            :    " +soup[6]*300+
                "\n     Tom Yam Soup               :    " +soup[7]*350+
                "\n     Whipped Egg Soup           :    " +soup[8]*250+
                "\n    ---------------------------------------" +
                "\n     SOUP Total Cost            :    " +soup[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     Delivery Charge            :   " +cost[3]+
                "\n     Sub Total                  :   " +cost[0]+
                "\n     VAT                        :   " +cost[1]+
                "\n     GRAND TOTAL                :   " +cost[2]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n\t\t  Thank You!"+
                "\n    * * * * * * * * * * * * * * * * * * * *\n\n" );
        }
        else
        JOptionPane.showMessageDialog(this, "Insert Correct Amount", "Error", JOptionPane.ERROR_MESSAGE);
        cash.setText("0");
        Card.setText("0");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cardMouseClicked

    private void cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new Cake().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new Drinks().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new Fried().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        new Pizza().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        new Soup().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jPanel2.setBackground(Color.BLACK);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jPanel2.setBackground(Color.BLUE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jPanel2.setBackground(Color.CYAN);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jPanel2.setBackground(Color.GREEN);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jPanel2.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jPanel2.setBackground(Color.RED);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jPanel2.setBackground(Color.WHITE);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Card;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton c;
    private javax.swing.JRadioButton card;
    private javax.swing.JTextField cash;
    private javax.swing.JRadioButton d;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton m;
    private javax.swing.JRadioButton v;
    // End of variables declaration//GEN-END:variables
}
