
import javax.swing.JOptionPane;

public class S extends javax.swing.JFrame {

    
    
    double [] i = new double [50];
    
    double [] cake = new double [10];
    double [] drink = new double [10];
    double [] fried = new double [10];
    double [] pizza = new double [10];
    double [] soup = new double [10];
    double [] cost = new double [4];
    
    
    public S() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        card = new javax.swing.JRadioButton();
        cash = new javax.swing.JTextField();
        Card = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c = new javax.swing.JRadioButton();
        d = new javax.swing.JRadioButton();
        m = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        v = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButton1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jRadioButton1.setText("CASH    :");

        card.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        card.setText("CARD   :");
        card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardMouseClicked(evt);
            }
        });
        card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardActionPerformed(evt);
            }
        });

        cash.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        cash.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Card.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        Card.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel2.setText("BDT");

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAYMENT");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel3.setText("BDT");

        c.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        c.setText("Credit Card");

        d.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        d.setText("Debit Card");

        m.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        m.setText("Master Card");

        jButton1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        v.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        v.setText("Visa Card");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Card, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Card, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cardMouseClicked

    private void cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cardActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //String pre = Order.gtotal.getText();

        String pre = Order.gtotal.getText();
        String CASH = cash.getText();
        String CARD = Card.getText();
        
        if (pre.equals(CASH) || pre.equals(CARD)){
            new Receipt().setVisible(true);
            
            
            
            
            
            
            
        cake[0] = Double.parseDouble(Order.black.getText());
        cake[1] = Double.parseDouble(Order.blueberry.getText());
        cake[2] = Double.parseDouble(Order.cappuccino.getText());
        cake[3] = Double.parseDouble(Order.dessert.getText());
        cake[4] = Double.parseDouble(Order.malted.getText());
        cake[5] = Double.parseDouble(Order.almond.getText());
        cake[6] = Double.parseDouble(Order.velvet.getText());
        cake[7] = Double.parseDouble(Order.strawberry.getText());
        cake[8] = Double.parseDouble(Order.vanilla.getText());
        cake[9] = Double.parseDouble(Order.cake_total.getText());
        
        drink[0] = Double.parseDouble(Order.coffee.getText());
        drink[1] = Double.parseDouble(Order.fruit.getText());
        drink[2] = Double.parseDouble(Order.lassi.getText());
        drink[3] = Double.parseDouble(Order.limes.getText());
        drink[4] = Double.parseDouble(Order.water.getText());
        drink[5] = Double.parseDouble(Order.scoop.getText());
        drink[6] = Double.parseDouble(Order.soft.getText());
        drink[7] = Double.parseDouble(Order.tamarind.getText());
        drink[8] = Double.parseDouble(Order.tea.getText());
        drink[9] = Double.parseDouble(Order.drinks_total.getText());
        
        fried[0] = Double.parseDouble(Order.bbq_fried.getText());
        fried[1] = Double.parseDouble(Order.beef_cheese.getText());
        fried[2] = Double.parseDouble(Order.steak.getText());
        fried[3] = Double.parseDouble(Order.beef_sandwich.getText());
        fried[4] = Double.parseDouble(Order.chicken_burger.getText());
        fried[5] = Double.parseDouble(Order.chicken_sandwich.getText());
        fried[6] = Double.parseDouble(Order.grilled_chicken.getText());
        fried[7] = Double.parseDouble(Order.pasta.getText());
        fried[8] = Double.parseDouble(Order.shrimp.getText());
        fried[9] = Double.parseDouble(Order.fried_total.getText());
        
        pizza[0] = Double.parseDouble(Order.bbq_pizza.getText());
        pizza[1] = Double.parseDouble(Order.beef_pepperoni.getText());
        pizza[2] = Double.parseDouble(Order.tandoori.getText());
        pizza[3] = Double.parseDouble(Order.gorgonzola.getText());
        pizza[4] = Double.parseDouble(Order.grilled.getText());
        pizza[5] = Double.parseDouble(Order.ortolana.getText());
        pizza[6] = Double.parseDouble(Order.roasted.getText());
        pizza[7] = Double.parseDouble(Order.veggie.getText());
        pizza[8] = Double.parseDouble(Order.zesty.getText());
        pizza[9] = Double.parseDouble(Order.pizza_total.getText());
        
        soup[0] = Double.parseDouble(Order.broccoli.getText());
        soup[1] = Double.parseDouble(Order.chicken_corn.getText());
        soup[2] = Double.parseDouble(Order.cream.getText());
        soup[3] = Double.parseDouble(Order.french.getText());
        soup[4] = Double.parseDouble(Order.minestrone.getText());
        soup[5] = Double.parseDouble(Order.mushroom.getText());
        soup[6] = Double.parseDouble(Order.prawn.getText());
        soup[7] = Double.parseDouble(Order.tom.getText());
        soup[8] = Double.parseDouble(Order.egg.getText());
        soup[9] = Double.parseDouble(Order.soup_total.getText());
        
        cost[0] = Double.parseDouble(Order.stotal.getText());
        cost[1] = Double.parseDouble(Order.vat.getText());
        cost[2] = Double.parseDouble(Order.gtotal.getText());
        cost[3] = Double.parseDouble(Order.HomeDl.getText());
        
        //String CName = Receipt.receipt.getText();
        //CustomerName.setText(CName);
        Receipt.receipt.append("\n\t Restaurant Management System"+
                                  "\n\t ============================\n"+
                "\n     Date: "+Order.date.getText()+ "\t   Time: "+Order.time.getText()+
                "\n     Customer Name: "+Order.CustomerName.getText()+
                "\n     Table NO: "+Order.TableNO.getText()+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     Black Forest Cake          :    " +cake[0]*850+
                "\n     Blueberry Cake             :    " +cake[1]*750+
                "\n     Cappuccino Cake            :    " +cake[2]*980+
                "\n     Chocolate Dessert Cake     :    " +cake[3]*720+
                "\n     Malted Chocolate Cake      :    " +cake[4]*950+
                "\n     Pistachio Almond Cake      :    " +cake[5]*850+
                "\n     Red Velvet Cake            :    " +cake[6]*800+
                "\n     Strawberry Chocolate Cake  :    " +cake[7]*730+
                "\n     Vanilla Cake               :    " +cake[8]*900+
                "\n    ---------------------------------------" +
                "\n     CAKE Total Cost            :    " +cake[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     Cold Coffee                :    " +drink[0]*175+
                "\n     Fruit Juice                :    " +drink[1]*120+
                "\n     Lassi                      :    " +drink[2]*100+
                "\n     Lemonade Limes             :    " +drink[3]*90+
                "\n     Mineral Water              :    " +drink[4]*60+
                "\n     Scoop Ice-cream            :    " +drink[5]*275+
                "\n     Soft Cold Drinks           :    " +drink[6]*150+
                "\n     Tamarind Juice             :    " +drink[7]*110+
                "\n     Tea                        :    " +drink[8]*70+
                "\n    ---------------------------------------" +
                "\n     DRINKS Total Cost          :    " +drink[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     BBQ Chicken Wings          :    " +fried[0]*550+
                "\n     Beef Cheese Burger         :    " +fried[1]*225+
                "\n     Beef Pepper Steak          :    " +fried[2]*275+
                "\n     Beef Sandwich              :    " +fried[3]*200+
                "\n     Chicken Burge              :    " +fried[4]*250+
                "\n     Chicken Sandwich           :    " +fried[5]*225+
                "\n     Grilled Chicken            :    " +fried[6]*350+
                "\n     Seafood Pasta              :    " +fried[7]*150+
                "\n     Shrimp Sandwich            :    " +fried[8]*180+
                "\n    ---------------------------------------" +
                "\n     FRIED Total Cost           :    " +fried[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     BBQ Chicken Pizza          :    " +pizza[0]*550+
                "\n     Beef Pepperoni Pizza       :    " +pizza[1]*675+
                "\n     Chicken Tandoori Pizza     :    " +pizza[2]*600+
                "\n     Gorgozola Cheese Pizza     :    " +pizza[3]*750+
                "\n     Grilled Chicken Pizza      :    " +pizza[4]*725+
                "\n     Pizza Ortolana             :    " +pizza[5]*720+
                "\n     Roasted Garlic Pizza       :    " +pizza[6]*650+
                "\n     Veggie Supreme Pizza       :    " +pizza[7]*575+
                "\n     Zesty Spicy Pizza          :    " +pizza[8]*700+
                "\n    ---------------------------------------" +
                "\n     PIZZA Total Cost           :    " +pizza[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     Broccoli Cheese Soup       :    " +soup[0]*275+
                "\n     Chicken Corn Soup          :    " +soup[1]*250+
                "\n     Cream Pane Soup            :    " +soup[2]*175+
                "\n     French Onion Soup          :    " +soup[3]*220+
                "\n     Minestrone Soup            :    " +soup[4]*280+
                "\n     Pane Mushroom Soup         :    " +soup[5]*200+
                "\n     Prawn Corn Soup            :    " +soup[6]*300+
                "\n     Tom Yam Soup               :    " +soup[7]*350+
                "\n     Whipped Egg Soup           :    " +soup[8]*250+
                "\n    ---------------------------------------" +
                "\n     SOUP Total Cost            :    " +soup[9]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+ 
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n     Home Delivery              :   " +cost[3]+
                "\n     Sub Total                  :   " +cost[0]+
                "\n     VAT                        :   " +cost[1]+
                "\n     GRAND TOTAL                :   " +cost[2]+
                "\n    = = = = = = = = = = = = = = = = = = = ="+
                "\n    = = = = = = = = = = = = = = = = = = = ="+               
                "\n\t\t  Thank You!"+ 
                "\n    * * * * * * * * * * * * * * * * * * * *\n\n" );
            
            
            
            
            
            
            
            
            
            
            
        }
        else
            JOptionPane.showMessageDialog(this, "Insert Correct Amount", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Card;
    private javax.swing.JRadioButton c;
    private javax.swing.JRadioButton card;
    private javax.swing.JTextField cash;
    private javax.swing.JRadioButton d;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton m;
    private javax.swing.JRadioButton v;
    // End of variables declaration//GEN-END:variables
}
